default: &default
  adapter: postgresql
  encoding: <%= ENV.fetch('DATABASE_ENCODING') { 'utf8' } %>
  pool: <%= ENV['DATABASE_POOL'] || ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL') %>
  min_messages: ERROR
  timeout: <%= ENV.fetch('DATABASE_TIMEOUT') { 5000 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
