# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6c763bad8c9276327668915f91f056eabbcf9480de306ccdbec5f93005376fd6089e8c900af599e39b246b22529d78e3d46bd62bc3028b97ae742da101b97687

test:
  secret_key_base: c036c5c4779c0452839520c55af7a560bed152ac48d99b37de6f2cd13a35e03870546eff59e6ed3a98f87286a5d6dfdf4dbb9c95305c739368be5457252ab5f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
